-- Tamper-evident security audit export and operational readiness metrics.

create table if not exists public.security_audit_events (
  sequence_number bigint generated by default as identity primary key,
  id uuid not null unique,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  project_key text not null,
  occurred_at timestamptz not null,
  event_type text not null,
  outcome text not null,
  actor_type text not null,
  actor_id text not null,
  capability text,
  request_id text,
  correlation_id text not null,
  source text not null,
  resource_type text,
  resource_id text,
  metadata jsonb not null default '{}'::jsonb,
  previous_hash text not null,
  event_hash text not null unique,
  constraint security_audit_project_key_check
    check (project_key ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
  constraint security_audit_event_type_check
    check (event_type ~ '^[a-z0-9][a-z0-9_.-]{2,127}$'),
  constraint security_audit_outcome_check
    check (outcome in ('accepted', 'denied', 'error', 'observed')),
  constraint security_audit_actor_type_check
    check (actor_type in ('machine', 'user', 'system')),
  constraint security_audit_previous_hash_check
    check (previous_hash ~ '^[a-f0-9]{64}$'),
  constraint security_audit_event_hash_check
    check (event_hash ~ '^[a-f0-9]{64}$'),
  constraint security_audit_metadata_object_check
    check (jsonb_typeof(metadata) = 'object')
);

create index if not exists security_audit_tenant_sequence_idx
  on public.security_audit_events(organization_id, project_key, sequence_number);
create index if not exists security_audit_tenant_time_idx
  on public.security_audit_events(organization_id, project_key, occurred_at desc);
create index if not exists security_audit_type_time_idx
  on public.security_audit_events(organization_id, project_key, event_type, occurred_at desc);
create index if not exists security_audit_request_idx
  on public.security_audit_events(organization_id, project_key, request_id)
  where request_id is not null;

alter table public.security_audit_events enable row level security;
revoke all on public.security_audit_events from public, anon, authenticated, service_role;
revoke all on sequence public.security_audit_events_sequence_number_seq
  from public, anon, authenticated, service_role;
grant select on public.security_audit_events to service_role;

create or replace function public.reject_security_audit_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'security_audit_events is append-only';
end;
$$;

drop trigger if exists security_audit_events_immutable
  on public.security_audit_events;
create trigger security_audit_events_immutable
before update or delete on public.security_audit_events
for each row execute function public.reject_security_audit_mutation();

create or replace function private.append_security_audit_event(
  p_organization_id uuid,
  p_project_key text,
  p_event_type text,
  p_outcome text,
  p_actor_type text,
  p_actor_id text,
  p_capability text,
  p_request_id text,
  p_correlation_id text,
  p_source text,
  p_resource_type text default null,
  p_resource_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  sequence_number bigint,
  event_id uuid,
  event_hash text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sequence bigint;
  v_event_id uuid := gen_random_uuid();
  v_occurred_at timestamptz := clock_timestamp();
  v_previous_hash text;
  v_event_hash text;
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_payload jsonb;
begin
  if p_project_key !~ '^[a-z0-9][a-z0-9_-]{0,63}$' then
    raise exception 'invalid audit project key';
  end if;
  if p_event_type !~ '^[a-z0-9][a-z0-9_.-]{2,127}$' then
    raise exception 'invalid audit event type';
  end if;
  if p_outcome not in ('accepted', 'denied', 'error', 'observed') then
    raise exception 'invalid audit outcome';
  end if;
  if p_actor_type not in ('machine', 'user', 'system') then
    raise exception 'invalid audit actor type';
  end if;
  if jsonb_typeof(v_metadata) <> 'object' or pg_column_size(v_metadata) > 16384 then
    raise exception 'audit metadata must be an object no larger than 16 KiB';
  end if;
  if nullif(btrim(p_actor_id), '') is null
    or nullif(btrim(p_correlation_id), '') is null
    or nullif(btrim(p_source), '') is null then
    raise exception 'audit actor, correlation, and source are required';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_organization_id::text || ':' || p_project_key, 0)
  );
  select audit.event_hash
    into v_previous_hash
    from public.security_audit_events audit
    where audit.organization_id = p_organization_id
      and audit.project_key = p_project_key
    order by audit.sequence_number desc
    limit 1;
  v_previous_hash := coalesce(v_previous_hash, repeat('0', 64));
  v_sequence := nextval('public.security_audit_events_sequence_number_seq'::regclass);
  v_payload := jsonb_build_object(
    'sequence_number', v_sequence,
    'id', v_event_id,
    'organization_id', p_organization_id,
    'project_key', p_project_key,
    'occurred_at', v_occurred_at,
    'event_type', p_event_type,
    'outcome', p_outcome,
    'actor_type', p_actor_type,
    'actor_id', p_actor_id,
    'capability', p_capability,
    'request_id', p_request_id,
    'correlation_id', p_correlation_id,
    'source', p_source,
    'resource_type', p_resource_type,
    'resource_id', p_resource_id,
    'metadata', v_metadata
  );
  v_event_hash := encode(
    sha256(convert_to(v_previous_hash || '|' || v_payload::text, 'UTF8')),
    'hex'
  );

  insert into public.security_audit_events (
    sequence_number,
    id,
    organization_id,
    project_key,
    occurred_at,
    event_type,
    outcome,
    actor_type,
    actor_id,
    capability,
    request_id,
    correlation_id,
    source,
    resource_type,
    resource_id,
    metadata,
    previous_hash,
    event_hash
  ) values (
    v_sequence,
    v_event_id,
    p_organization_id,
    p_project_key,
    v_occurred_at,
    p_event_type,
    p_outcome,
    p_actor_type,
    p_actor_id,
    p_capability,
    p_request_id,
    p_correlation_id,
    p_source,
    p_resource_type,
    p_resource_id,
    v_metadata,
    v_previous_hash,
    v_event_hash
  );

  return query select v_sequence, v_event_id, v_event_hash;
end;
$$;

create or replace function public.verify_security_audit_chain(
  p_organization_id uuid,
  p_project_key text
)
returns table (
  valid boolean,
  events_checked bigint,
  first_bad_sequence bigint,
  head_hash text
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  audit record;
  expected_previous text := repeat('0', 64);
  expected_hash text;
  checked bigint := 0;
  current_head text := repeat('0', 64);
  payload jsonb;
begin
  for audit in
    select *
      from public.security_audit_events
      where organization_id = p_organization_id
        and project_key = p_project_key
      order by sequence_number
  loop
    payload := jsonb_build_object(
      'sequence_number', audit.sequence_number,
      'id', audit.id,
      'organization_id', audit.organization_id,
      'project_key', audit.project_key,
      'occurred_at', audit.occurred_at,
      'event_type', audit.event_type,
      'outcome', audit.outcome,
      'actor_type', audit.actor_type,
      'actor_id', audit.actor_id,
      'capability', audit.capability,
      'request_id', audit.request_id,
      'correlation_id', audit.correlation_id,
      'source', audit.source,
      'resource_type', audit.resource_type,
      'resource_id', audit.resource_id,
      'metadata', audit.metadata
    );
    expected_hash := encode(
      sha256(convert_to(expected_previous || '|' || payload::text, 'UTF8')),
      'hex'
    );
    if audit.previous_hash <> expected_previous or audit.event_hash <> expected_hash then
      return query select false, checked, audit.sequence_number, current_head;
      return;
    end if;
    checked := checked + 1;
    expected_previous := audit.event_hash;
    current_head := audit.event_hash;
  end loop;
  return query select true, checked, null::bigint, current_head;
end;
$$;

create or replace function public.export_security_audit_events(
  p_organization_id uuid,
  p_project_key text,
  p_after_sequence bigint default 0,
  p_limit integer default 100
)
returns setof public.security_audit_events
language sql
stable
security invoker
set search_path = ''
as $$
  select audit.*
  from public.security_audit_events audit
  where audit.organization_id = p_organization_id
    and audit.project_key = p_project_key
    and audit.sequence_number > greatest(p_after_sequence, 0)
  order by audit.sequence_number
  limit least(greatest(p_limit, 1), 500);
$$;

create or replace function public.get_loopgraph_operational_snapshot(
  p_organization_id uuid,
  p_project_key text
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'database_ready', true,
    'captured_at', now(),
    'machine_requests_5m', (
      select count(*)
      from public.machine_request_receipts receipt
      where receipt.organization_id = p_organization_id
        and receipt.project_key = p_project_key
        and receipt.received_at >= now() - interval '5 minutes'
    ),
    'machine_rate_limited_5m', (
      select count(*)
      from public.machine_request_receipts receipt
      where receipt.organization_id = p_organization_id
        and receipt.project_key = p_project_key
        and receipt.decision = 'rate_limited'
        and receipt.received_at >= now() - interval '5 minutes'
    ),
    'machine_denied_5m', (
      select count(*)
      from public.security_audit_events audit
      where audit.organization_id = p_organization_id
        and audit.project_key = p_project_key
        and audit.event_type = 'machine.request.denied'
        and audit.occurred_at >= now() - interval '5 minutes'
    ),
    'audit_events_total', (
      select count(*)
      from public.security_audit_events audit
      where audit.organization_id = p_organization_id
        and audit.project_key = p_project_key
    ),
    'audit_head_sequence', coalesce((
      select max(audit.sequence_number)
      from public.security_audit_events audit
      where audit.organization_id = p_organization_id
        and audit.project_key = p_project_key
    ), 0),
    'last_machine_request_at', (
      select max(receipt.received_at)
      from public.machine_request_receipts receipt
      where receipt.organization_id = p_organization_id
        and receipt.project_key = p_project_key
    )
  );
$$;

-- Replace the request guard so every durable authorization decision is appended to the
-- tenant audit chain in the same database transaction.
create or replace function public.authorize_machine_request(
  p_organization_id uuid,
  p_project_key text,
  p_credential_id text,
  p_capability text,
  p_request_id text,
  p_request_hash text,
  p_requested_at timestamptz,
  p_rate_limit integer
)
returns table (
  authorized boolean,
  reason text,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_receipt uuid;
  current_count integer;
  current_window timestamptz := date_trunc('minute', now());
begin
  if p_rate_limit < 1 or p_rate_limit > 10000 then
    perform private.append_security_audit_event(
      p_organization_id, p_project_key, 'machine.request.denied', 'denied',
      'machine', p_credential_id, p_capability, p_request_id, p_request_id,
      'machine_request_guard', null, null, jsonb_build_object('reason', 'invalid_rate_limit')
    );
    return query select false, 'invalid_rate_limit'::text, null::integer;
    return;
  end if;

  delete from public.machine_request_receipts
    where organization_id = p_organization_id
      and expires_at < now();
  delete from public.machine_rate_limit_windows
    where organization_id = p_organization_id
      and updated_at < now() - interval '1 day';

  insert into public.machine_request_receipts (
    organization_id,
    project_key,
    credential_id,
    capability,
    request_id,
    request_hash,
    requested_at
  ) values (
    p_organization_id,
    p_project_key,
    p_credential_id,
    p_capability,
    p_request_id,
    p_request_hash,
    p_requested_at
  )
  on conflict (organization_id, project_key, credential_id, request_id) do nothing
  returning id into inserted_receipt;

  if inserted_receipt is null then
    perform private.append_security_audit_event(
      p_organization_id, p_project_key, 'machine.request.denied', 'denied',
      'machine', p_credential_id, p_capability, p_request_id, p_request_id,
      'machine_request_guard', null, null, jsonb_build_object('reason', 'replayed_request')
    );
    return query select false, 'replayed_request'::text, null::integer;
    return;
  end if;

  insert into public.machine_rate_limit_windows (
    organization_id,
    project_key,
    credential_id,
    capability,
    window_started_at,
    request_count
  ) values (
    p_organization_id,
    p_project_key,
    p_credential_id,
    p_capability,
    current_window,
    1
  )
  on conflict (
    organization_id,
    project_key,
    credential_id,
    capability,
    window_started_at
  ) do update
    set request_count = public.machine_rate_limit_windows.request_count + 1,
        updated_at = now()
    where public.machine_rate_limit_windows.request_count < p_rate_limit
  returning request_count into current_count;

  if current_count is null then
    update public.machine_request_receipts
      set decision = 'rate_limited'
      where id = inserted_receipt;
    perform private.append_security_audit_event(
      p_organization_id, p_project_key, 'machine.request.denied', 'denied',
      'machine', p_credential_id, p_capability, p_request_id, p_request_id,
      'machine_request_guard', null, null, jsonb_build_object('reason', 'rate_limited')
    );
    return query select false, 'rate_limited'::text,
      greatest(1, 60 - extract(second from now())::integer);
    return;
  end if;

  perform private.append_security_audit_event(
    p_organization_id, p_project_key, 'machine.request.authorized', 'accepted',
    'machine', p_credential_id, p_capability, p_request_id, p_request_id,
    'machine_request_guard', null, null,
    jsonb_build_object('request_hash', p_request_hash, 'requested_at', p_requested_at)
  );
  return query select true, 'accepted'::text, null::integer;
end;
$$;

revoke all on function public.reject_security_audit_mutation() from public, anon, authenticated;
revoke all on function private.append_security_audit_event(
  uuid, text, text, text, text, text, text, text, text, text, text, text, jsonb
) from public, anon, authenticated, service_role;
revoke all on function public.verify_security_audit_chain(uuid, text)
  from public, anon, authenticated;
revoke all on function public.export_security_audit_events(uuid, text, bigint, integer)
  from public, anon, authenticated;
revoke all on function public.get_loopgraph_operational_snapshot(uuid, text)
  from public, anon, authenticated;
grant execute on function public.verify_security_audit_chain(uuid, text) to service_role;
grant execute on function public.export_security_audit_events(uuid, text, bigint, integer)
  to service_role;
grant execute on function public.get_loopgraph_operational_snapshot(uuid, text) to service_role;
